### ISSUE TITLE
Nicht im Installer verfügbar, nicht über die Suche verfügbar

### ISSUE THREAD

**Issue by AWqxKAWERbXo** [aeberhard/xoutputfilter#2]
Hi!

Wäre super, wenn das Addon auch für Redaxo 4.4, 4.5 (und 4.6) verfügbar wäre. Es funktioniert ja einwandfrei unter 4.5, im Prinzip müsste man nur im redaxo.org-Addons-Bereich die Kompatibilität hochstufen, oder?

VG und Vielen Dank für das tolle Addon

**Comment by aeberhard** [comment]
Hi Alex,
ich habe die Kompatibilität jetzt mal hochgestuft. Probier es mal aus.
LG Andreas

**Comment by AWqxKAWERbXo** [comment]
super, klappt, danke :)
